---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
  annotations:
    
spec:
  ports:
  - name: http-{{ .Release.Name }}-backend-{{ .Values.backend.version }}
    port: 80
    targetPort: 80
  selector:
    app: backend